name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-versions: [8, 11, 17]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-versions }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-versions }}
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
